### ISSUE TITLE
Support for "Tiling Assistant"

### ISSUE THREAD

**Issue by Magnotec1** [mipmip/gnome-shell-extensions-useless-gaps#11]
[Tiling Assistant](https://github.com/Leleat/Tiling-Assistant) basically just adds more spots to tile to, e.g; you could drag a window to the bottom of the screen and it would become horizontally tiled. As of right now, it does not work with this extension.

**Comment by mipmip** [comment]
Correct. This extension was made to work with the minimal tiling functionality of mutter only. You can better submit a request in the Tiling Assistant project for implementing gaps.
