### ISSUE TITLE
Avoid Dash To Dock?

### ISSUE THREAD

**Issue by MelonFunction** [mipmip/gnome-shell-extensions-useless-gaps#13]
Is it possible to avoid dash to dock?
A simple workaround would be to have options to set each margin, then bottom margin can be increased manually to avoid that part of the screen.

**Comment by mipmip** [comment]
That could be an option. PR’s are welcome.

**Comment by MelonFunction** [comment]
I'll get to work on it :)

**Comment by mipmip** [comment]
I've implemented custom margins.
