### ISSUE TITLE
Version Bump?

### ISSUE THREAD

**Issue by jonseppanen** [mipmip/gnome-shell-extensions-useless-gaps#15]
Could we get gnome 43 support please?

Thanks!

**Comment by mipmip** [comment]
@jonseppanen, can you confirm it's working correctly in Gnome 43? I was not able to test it myself.

**Comment by jonseppanen** [comment]
Yes, it works perfectly on gnome 43 when bumping the manifest file.

**Comment by mipmip** [comment]
@jonseppanen If you like your can send a PR.
