### ISSUE TITLE
Gnome 44 incompatibility

### ISSUE THREAD

**Issue by Vertecedoc4545** [mipmip/gnome-shell-extensions-useless-gaps#20]

**Comment by mipmip** [comment]
Did you test this extension in 44 and encountered specific problems?

**Comment by graygrotesque** [comment]
I can't activate it in Arch, 44.1

**Comment by mipmip** [comment]
You can install the extension manually by cloning the repo and then run

``
./install.sh local-install
```
After restarting or reloading gnome it should work. You might need to change the versions in metadata.json.

I did not test useless-gaps myself in 44. If you all say it's working okay, I will upload a new version to the gnome extension registry.

**Comment by TheArctesian** [comment]
I'll test it out in a vm now

**Comment by TheArctesian** [comment]
Just tested it worked fine after a local install and system reset, go ahead and upload

**Comment by mipmip** [comment]
Thanks @TheArctesian New version has been uploaded.
