### ISSUE TITLE
Right split window on second monitor is moved to first monitor

### ISSUE THREAD

**Issue by jqno** [mipmip/gnome-shell-extensions-useless-gaps#21]
I have two monitors: the primary is on the left and the secondary is on the right. Whenever I'm working on the secondary (right) monitor, and I want to tile a window to the right half of that monitor, it gets moved to the right half of the primary monitor instead.

I traced it to this line:

https://github.com/mipmip/gnome-shell-extensions-useless-gaps/blob/4ed8e31d6b9d4b7b90b93d6ed4f7f333d815bde8/src/extension.js#L82

It doesn't reference `rects.window.x`, which would explain why it moves to the primary monitor in my setup.

I did some experimenting (also with placing my secondary monitor to the left and the top of the primary one), and changing it to this solves the issue for me:

```js
xStart = rects.window.x + rects.window.w - this.marginRight - this.gapSize - newWidth;
```

I used subtraction because I couldn't get the placing quite right using addition like in the original, and this seemed simple and clear enough.

If you agree with my assessment, I'd be happy to submit a PR.

BTW, I love this extension. It's simple and does exactly what I want and no more.

**Comment by mipmip** [comment]
Hi @jqno! You're very welcome to submit a PR. This problem was found earlier by others and I stopped using two monitors myself.

**Comment by jqno** [comment]
I see how that makes it harder to debug these kinds of things 🙂. I submitted the PR!
