### ISSUE TITLE
Please add Gnome 45 support?

### ISSUE THREAD

**Issue by memory-colors** [mipmip/gnome-shell-extensions-useless-gaps#23]
Hello!

I love love LOVE this extension. Unfortunately it's a no-go on Gnome 45. Would very much appreciate an update.

Thanks so much!!

**Comment by 3ibod** [comment]
yes please

**Comment by mipmip** [comment]
I will find some spare minutes to realize this...

**Comment by StarNumber12046** [comment]
any progress?

**Comment by mipmip** [comment]
After my holiday. I promise. PR is welcome btw.

**Comment by poinck** [comment]
I have tried make it work using [this](https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/) blog, but I am stuck.

- I have changed all the imports according to ECMA6
- extended the new `Extension` class in favor of `ExtensionUtils`
- **but** now I see an `Error: UselessGapsExtension does not pass metadata to parent`. I don't know where this message is coming from

**Comment by poinck** [comment]
![image](https://github.com/mipmip/gnome-shell-extensions-useless-gaps/assets/1297960/1aadd65c-3d40-4ba4-83e5-db4f086a98a2)

I got it to work, but the preference window is still broken, because this needs to be done with this import:

```
import { ExtensionPreferences } from "resource:///org/gnome/Shell/Extensions/js/extensions/prefs.js";
```

I will try to prepare a PR, but it will definitely need some more love. *(I had a look at the ForgeExtension for reference).*

**Comment by poinck** [comment]
If someone wants to help or test; [here](https://github.com/mipmip/gnome-shell-extensions-useless-gaps/pull/25) is my draft PR.

**Comment by mipmip** [comment]
waiting for the store review, but you can grap the repo if you like.

**Comment by StarNumber12046** [comment]
👀

**Comment by jqno** [comment]
The new version still hasn't appeared on extensions.gnome.org yet. Was there an issue with the review?
(I installed manually from the repo, and it works just fine.)

**Comment by mipmip** [comment]
> The new version still hasn't appeared on extensions.gnome.org yet. Was there an issue with the review? (I installed manually from the repo, and it works just fine.)

I got a late review, but I have to do some small changes. Did not have time for this yet.

**Comment by mipmip** [comment]
@jqno @poinck  @poinck  @3ibod  @StarNumber12046 it's live.

**Comment by StarNumber12046** [comment]
I've been using it since it got released on upstream
