### ISSUE TITLE
Gnome Shell 46 support?

### ISSUE THREAD

**Issue by mkalinski** [mipmip/gnome-shell-extensions-useless-gaps#27]
I see that in the [extension metadata](https://github.com/mipmip/gnome-shell-extensions-useless-gaps/blob/main/src/metadata.json) that it's supposed to support shell version 46.

However for some reason, [the extension's EGO page](https://extensions.gnome.org/extension/4684/useless-gaps/) claims there's no version compatible with 46, and my Gnome Shell disabled the extension (for version 16, the same as in the main branch metadata file) after update to 46.

**Comment by jqno** [comment]
You can install it locally: clone this repository and run `./install.sh local-install`. It's not ideal but I've done it too and can confirm that it works

**Comment by mipmip** [comment]
it's in the store
