### ISSUE TITLE
Toggle Maximization State without closing application (gnome 3.36)

### ISSUE THREAD

**Issue by Dylansc22** [mipmip/gnome-shell-extensions-useless-gaps#3]
**Issue:** 
'Toggle Maximization State' (the customizable shortcut in Settings > Keyboard Shortcuts) does not work when useless-gaps is installed. When toggling from maximized-state (with padding) to the unmaximized state, the window cycles itself back to the same size onclick. (See attached gif below). I imagine this is because when useless-gap is enabled, the window is technically never "maximized", thus using a shortcut that cycles from "maximized" to "unmaximized" is causing some failure in some sort of `if (..) then { ... } logic... (?)

**Expected Behavior** 
While useless-gap is enabled and clicking my 'Toggle Maximization State' shortcut, the window should toggle between a **padded-**maximized/**padded**-unmaximized window size.

**Computer:** 
Ubuntu 20.04
Gnome 3.36.8

Can this be fixed? Or is this a limitation of how useless-gap adds padding to its windows?

![Screencast from 29-12-21 13_16_32](https://user-images.githubusercontent.com/7850929/147700997-7b606a71-373a-4e44-b639-a4c5a4a07ad2.gif)

**Comment by mipmip** [comment]
With my current knowledge this is hard to fix. Useless Gaps needs to unmaximize a window before it can set the gaps. After this it's previous unmaximized position and size is overwritten in memory. I'll try to find an solution. Suggestions are welcome.

**Comment by Dylansc22** [comment]
Best of luck! Love the extension for as silly as it is! It actually makes starring at my computer feel more "open" and "airy" during marathon work sessions. I use it in combo with Variety (for wallpapers), and Dynamic Panel Transparency (for the transparent top bar). The combo makes work slightly less terrible, haha =P

**Comment by sk22** [comment]
maybe there's some clues on how this can be implemented in this extension? https://github.com/necropolina/gnome-edge-gap

**Comment by mipmip** [comment]
This issue is not relevant anymore as Useless Gabs stopped support of Gnome 3.x versions.
