### ISSUE TITLE
Support for Gnome 42

### ISSUE THREAD

**Issue by logan-connolly** [mipmip/gnome-shell-extensions-useless-gaps#9]
Hi @mipmip just want to first say thank you for the awesome extension! I didn't realize how dependent I was on useless gaps until I updated to Gnome 42 to suddenly find myself _gapless_.

I am not sure if this update is on your radar, but I just wanted to raise the issue in case others come here wondering the same. In the meantime I will likely be reverting back to 41 because I need my gaps :laughing: 

Thanks again!

**Comment by quebin31** [comment]
I did the modification to the `metadata.json` file to add support for 42 and I haven't seen any issues so far, I'm using Gnome 42 in Arch Linux

**Comment by mipmip** [comment]
@quebin31 you could submit a PR. Happy to merge.
